### ISSUE TITLE
ino-chip: properties have no effect on the appearance of the component in Angular

### ISSUE THREAD

**Issue by P1NHE4D** [inovex/elements#166] opened 2020-11-03 14:13 UTC
### Describe the bug
The `ino-chip` component comes with a set of properties that can be used to alter the appearance of the component. However, it appears that the properties are not working as intended in Angular projects. More specifically, I tried to set `inoFill` to `outline` and `inoColorScheme` to `primary`, but the appearance of the chip stays the same. Incorporating the component into a `ino-chip-set` has no effect. 

### To Reproduce
1. Setup a simple angular project (`ng new test`)
2. Add `"@inovex.de/elements-angular": "^2.0.0"` to the `package.json` file
3. Run `npm i`
4. Add `InoElementsModule.forRoot()` to the imports array in the `app.module.ts` file
5. Replace the sample template in the `app.component.html` file with the `ino-chip` component
6. Set `inoFill` to `outline` and `inoColorScheme` to `primary`
7. Run `npm start`
8. Navigate to `localhost:4200` and observe the error. Setting the properties did not change the appearance. 

### Expected behavior
The properties should affect the appearance of the `ino-chip` component.

### Screenshots
<img width="62" alt="Screenshot 2020-11-03 at 15 09 24" src="https://user-images.githubusercontent.com/44554211/97995037-50c98600-1de6-11eb-9e5c-902f1308f341.png">
<img width="670" alt="Screenshot 2020-11-03 at 15 12 33" src="https://user-images.githubusercontent.com/44554211/97995409-c0d80c00-1de6-11eb-8955-05faf04fc852.png">

### Your Environment
 

| Software | Version |
| -------- | ------- |
| @inovex.de/elements | 2.0.0 (bug is also present in v1.2.0)
| Browser | Safari 
| Operating System | Mac OS
| Angular Version | 10

**Comment by janivo** [comment] 2020-12-15 15:42
It's working as intended in my Angular 10 project with the elements version 2.2.1. Could you check if this example works for you now?
```

<ino-chip
	  ino-color-scheme="primary"
	  ino-fill="outline"
	  ino-label="Release Notes"
	  ino-icon="number"
></ino-chip>


```

**Comment by silentHoo** [comment] 2021-01-29 14:09
Should be fixed with https://github.com/inovex/elements/issues/243

**Closed** 2021-07-28 15:43 UTC
Labels: bug, est-low
